[2022-07-04 17:08:06,106] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_python_operator.middle_task manual__2022-07-04T17:08:04.156281+00:00 [queued]>
[2022-07-04 17:08:06,121] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_python_operator.middle_task manual__2022-07-04T17:08:04.156281+00:00 [queued]>
[2022-07-04 17:08:06,121] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 17:08:06,121] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-07-04 17:08:06,121] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 17:08:06,153] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): middle_task> on 2022-07-04 17:08:04.156281+00:00
[2022-07-04 17:08:06,157] {standard_task_runner.py:52} INFO - Started process 2976 to run task
[2022-07-04 17:08:06,159] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_python_operator', 'middle_task', 'manual__2022-07-04T17:08:04.156281+00:00', '--job-id', '394', '--raw', '--subdir', 'DAGS_FOLDER/my_python_operator_dag.py', '--cfg-path', '/tmp/tmpyh6e_ijs', '--error-file', '/tmp/tmpl9xitgs6']
[2022-07-04 17:08:06,160] {standard_task_runner.py:80} INFO - Job 394: Subtask middle_task
[2022-07-04 17:08:06,219] {task_command.py:370} INFO - Running <TaskInstance: my_python_operator.middle_task manual__2022-07-04T17:08:04.156281+00:00 [running]> on host a84f4c234c47
[2022-07-04 17:08:06,283] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=giang
AIRFLOW_CTX_DAG_ID=my_python_operator
AIRFLOW_CTX_TASK_ID=middle_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T17:08:04.156281+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-04T17:08:04.156281+00:00
[2022-07-04 17:08:06,284] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_python_operator_dag.py", line 15, in middle_task
    print('{0} executed at {1}'.format(name,date.strftime("%b %d, %Y")))
AttributeError: 'builtin_function_or_method' object has no attribute 'strftime'
[2022-07-04 17:08:06,290] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=my_python_operator, task_id=middle_task, execution_date=20220704T170804, start_date=20220704T170806, end_date=20220704T170806
[2022-07-04 17:08:06,300] {standard_task_runner.py:97} ERROR - Failed to execute job 394 for task middle_task ('builtin_function_or_method' object has no attribute 'strftime'; 2976)
[2022-07-04 17:08:06,331] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-04 17:08:06,353] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
